---
dependencies: []

galaxy_info:
  role_name: docker
  author: odgon
  description: Docker pour Linux.
  company: "only training.."
  license: "license (BSD, MIT)"
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
